### ISSUE TITLE
OSX: DOCKER: Connection to 192.168.59.104 timed out

### ISSUE THREAD

**Issue by Arsca** [artificialio/sane#116]
Hi,
Coming from SailsJS and trying to install sane with docker on OSX with boot2docker installed and functional:

> sane new todoApp --docker -d mongo --verbose
Sane version: 0.0.24
Setting up Sails project and downloading latest Docker Containers.
sails version: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 299, in run
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.project", line 190, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 350, in start_or_create_containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 122, in containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/docker.client", line 519, in containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/docker.client", line 81, in _get
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 395, in get
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: (<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x10e7af710>, 'Connection to 192.168.59.104 timed out. (connect timeout=60)')
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 299, in run
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.project", line 190, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 350, in start_or_create_containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 122, in containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/docker.client", line 519, in containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/docker.client", line 81, in _get
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 395, in get
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: (<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x1063fe710>, 'Connection to 192.168.59.104 timed out. (connect timeout=60)')
`docker-compose run server sails new .` failed with code 255

**Comment by Globegitter** [comment]
Glad you found this project. Is your boot2docker vm running? Does `boot2docker ssh` work? Can you try `boot2docker restart` if it is? Boot2docker unfortunately does seem to be a source of some errors on Mac.

**Comment by Arsca** [comment]
Restarted b2d  and manually set the $DOCKER_HOST for the session and all ok.

Thanks :)
