### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by devongennuso** [artificialio/sane#163]
sane -V 0.0.24
ember -v
version: 0.2.5
node: 0.12.3
npm: 2.10.0

I'm using mongodb as my database. I'm getting this error everytime I generate a new project.

Machine details:
OS X Yosemite
Version: 10.10.3
MacBook Pro (Retina, 15-inch, Mid 2014)

client   | Error proxying to http://127.0.0.1:1337
client   | socket hang up
client   | Error: socket hang up
client   |     at createHangUpError (_http_client.js:215:15)
client   |     at Socket.socketCloseListener (_http_client.js:247:23)
client   |     at Socket.emit (events.js:129:20)
client   |     at TCP.close (net.js:485:12)

**Comment by IanVS** [comment]
Hi, were you able to figure this out, or is it still a problem?  You can also try using the latest beta version of sane with `npm install -g sane-cli@0.1.0-beta.2`

**Comment by movses** [comment]
Hi, I have the same issue, switching to sane-cli@0.1.0-beta.2 didn't help.
ember-cli: 2.5.1, node: 4.3.0, sane: 0.0.24
Seems the problem is server running on https://127.0.0.1:1337, 
but client tries to reach it on http://127.0.0.1:1337
Any ideas?

**Comment by jamemackson** [comment]
@movses if you're running your server on https, can you pass the full url you'd like your client to connect to when you're calling `io.socket.get(...)` when you initialize the socket from your client?

**Comment by movses** [comment]
The following command inside 'client' directory resolved my issue.
$ember server --ssl=true --proxy=https://ipaddress:1337
