### ISSUE TITLE
sane new isnt working for me on Sane version: 0.1.0-beta.1

### ISSUE THREAD

**Issue by HERRKIN** [artificialio/sane#170]
```
 Detected different versions for sane's locally installed ember-cli (0.2.7) and your global one (undefined).
Want to use sane's local Ember? (y/n):  (y) n
Sane version: 0.1.0-beta.1

Setting up Sails project locally.
```

I tried y and n, in both cases it only creates the server directory. this is the ls

```
fig.yml  package.json  server

```

**Comment by IanVS** [comment]
Can you please try installing SANE from the master repo with `npm I -g artificialio/sane` and try again?  There is a fix in the master version which isn't in the current beta, and I'm hoping that fixes your problem.

**Comment by HERRKIN** [comment]
well same thing, maybe I broke something up whie installing different version of sails? I had the npm default version, later I installed the beta without uninstalling the previous one, and now I did the same, just npm i -g without uninstalling the previous one.

**Comment by HERRKIN** [comment]
I uninstalled sane-cli from my computer, then installed the one you say here. 
current version is 
```
Sane version: 0.1.0-beta.1
```
I did sane new, it said it didnt recognize the sails version but it did complete the new command (or I think so) I saw the folders and it seems to be ok. 

I am trying to learn sane-auth so after that I immediately tried to install sane-auth, this was the result: 

```
herrkin@truevisionhd:~/testap$ sane install sane-auth
sane-auth succesfully installed. Running it's default generator now...
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at closestPackageJSON$ (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/lib/tasks/Project.js:23:29)
    at tryCatch (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:305:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at invoke (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:132:37)
    at /home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:166:18
    at run (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at doNTCallback0 (node.js:408:9)
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at closestPackageJSON$ (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/lib/tasks/Project.js:23:29)
    at tryCatch (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:305:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at invoke (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:132:37)
    at /home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:166:18
    at run (/home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /home/herrkin/.nvm/versions/io.js/v2.3.1/lib/node_modules/sane-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at doNTCallback0 (node.js:408:9)
```

**Comment by HERRKIN** [comment]
well I was totally wrong, new command only creates this
api  frontend  node_modules  package.json
folders are empty

**Comment by IanVS** [comment]
@HERRKIN can you please try with `beta.2`?

**Comment by IanVS** [comment]
Closing due to no response.
