### ISSUE TITLE
Error when using ember global version

### ISSUE THREAD

**Issue by diofinus** [artificialio/sane#175]
Try to do `sane new` but got error when setting up ember

```
Setting up Ember project locally.
ember-cli Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at AddonDiscovery.<anonymous> (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/addon-discovery.js:107:24)
    at Array.map (native)
    at AddonDiscovery.discoverFromDependencies (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/addon-discovery.js:97:68)
    at AddonDiscovery.discoverProjectAddons (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/addon-discovery.js:45:31)
    at Project.discoverAddons (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/project.js:317:40)
    at Project.initializeAddons (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/project.js:336:8)
    at Project.eachAddonCommand (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/models/project.js:389:10)
    at module.exports (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/cli/lookup-command.js:34:13)
    at CLI.<anonymous> (/home/dio/.nvm/versions/node/v0.12.4/lib/node_modules/ember-cli/lib/cli/cli.js:35:26)
`ember new client --skip-git` failed with code 1
```

ubuntu 14.04
sane version 0.0.24
ember 1.13.1
node 0.12.4
npm 2.12.1

**Comment by IanVS** [comment]
Can you try updating to `sane-cli@0.1.0-beta.2` and trying again?

**Comment by diofinus** [comment]
updating sane-cli to `0.1.0-beta.2` solved the problem :+1:
