### ISSUE TITLE
Look into ember serve EHOSTUNREACH issue

### ISSUE THREAD

**Issue by Globegitter** [artificialio/sane#30]
Sometimes you seem to get the bug:
```
client   | Error: connect EHOSTUNREACH
client   |     at errnoException (net.js:904:11)
client   |     at connect (net.js:766:19)
client   |     at net.js:845:9
client   |     at asyncCallback (dns.js:68:16)
client   |     at Object.onanswer [as oncomplete] (dns.js:121:9)
```
Source of error has not been identified yet, seems to happen quite randomly so far.

web dev console shows:
```
WebSocket connection to 'ws://0.0.0.0:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by Globegitter** [comment]
Seems like this got fixed by 38c1b45.
