### ISSUE TITLE
'sane new project --docker --verbose -d mongo' gives error than hangs

### ISSUE THREAD

**Issue by mgenev** [artificialio/sane#85]
I'm using iojs 1.3 with the latest version of sane from the master branch here, also tried latest on npm. Struggled with this for a while, only worked once out of 20ish times, no idea what differed, but afterward the project still wouldn't work. Full log below:

```
➜  Projects  sane new meetup-demo --verbose --docker -d mongo
Detected different versions for sane's locally installed ember-cli (0.1.15) and your global one (0.2.0). Want to use sane's one? (y/n):  (y) n
Sane version: 0.0.23

Setting up Sails project and downloading latest Docker Containers.
sails version: Creating meetupdemo_db_1...
Pulling image mongo:latest...
















mongo:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Downloaded newer image for mongo:latest
Pulling image artificial/docker-sails:stable-pm2...














Status: Downloaded newer image for artificial/docker-sails:stable-pm2
info: Created a new Sails app `server`!
npm WARN optional dep failed, continuing fsevents@0.3.5
Installing Sails packages for tooling via npm...
> kerberos@0.0.7 install /server/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-nstalling Sails packages for tooling via npm....-
> bson@0.2.19 install /server/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

Installing Sails packages for tooling via npm.pluralize@1.1.2 node_modules/pluralize

sails-generate-ember-blueprints@0.0.3 node_modules/sails-generate-ember-blueprints
└── merge-defaults@0.2.1

morgan@1.5.1 node_modules/morgan
├── basic-auth@1.0.0
├── depd@1.0.0
├── debug@2.1.1 (ms@0.6.2)
└── on-finished@2.2.0 (ee-first@1.1.0)

lodash@2.4.1 node_modules/lodash

sails-hook-autoreload@0.11.4 node_modules/sails-hook-autoreload
└── chokidar@1.0.0-rc3 (async-each@0.1.6, is-binary-path@1.0.0, glob-parent@1.0.0, anymatch@1.1.0, readdirp@1.3.0)

sails-mongo@0.10.5 node_modules/sails-mongo
├── waterline-errors@0.10.1
├── async@0.8.0
├── waterline-cursor@0.0.5 (async@0.9.0)
└── mongodb@1.4.26 (readable-stream@1.0.33, kerberos@0.0.7, bson@0.2.19)
Installing Sails packages for tooling via npm....Running generator (sails-generate-ember-blueprints) @ `/server`...
Installing Sails packages for tooling via npm.info: Created a new ember-blueprints!
Installed Sails packages for tooling via npm.

Setting up Ember project locally.
ember-cli version: 0.2.0-beta.1
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Running tooling scrips for Sane...unbuild grunt-contrib-concat@0.3.0
unbuild grunt-contrib-less@0.11.1
unbuild grunt-contrib-cssmin@0.9.0
unbuild grunt-contrib-jst@0.6.0
unbuild grunt-contrib-uglify@0.4.1
unbuild grunt@0.4.2
unbuild grunt-contrib-clean@0.5.0
unbuild grunt-contrib-copy@0.5.0
unbuild ejs@0.8.8
unbuild grunt-sync@0.0.8
unbuild grunt-contrib-watch@0.5.3
unbuild grunt-sails-linker@0.9.6
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "node" "/usr/local/bin/npm" "rm" "grunt" "ejs" "grunt-contrib-clean" "grunt-contrib-concat" "grunt-contrib-copy" "grunt-contrib-cssmin" "grunt-contrib-jst" "grunt-contrib-less" "grunt-contrib-uglify" "grunt-contrib-watch" "grunt-sails-linker" "grunt-sync" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.0
npm ERR! path /server/node_modules
npm ERR! code EINVAL
npm ERR! errno -22

npm ERR! EINVAL, scandir '/server/node_modules'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /server/npm-debug.log
Running tooling scrips for Sane....`fig run server npm rm grunt ejs grunt-contrib-clean grunt-contrib-concat grunt-contrib-copy grunt-contrib-cssmin grunt-contrib-jst grunt-contrib-less grunt-contrib-uglify grunt-contrib-watch grunt-sails-linker grunt-sync --save` failed with code 234
```

**Comment by mgenev** [comment]
After installing whether I got that error or the one time I did not, when I generate my model, I try to hit it in the browser and I get this:
```
server_1 | /server/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:246
server_1 |         throw message;      
server_1 |               ^
server_1 | TypeError: undefined is not a function
server_1 |     at Object.sendOK (/server/api/responses/ok.js:44:19)
server_1 |     at ServerResponse.bound [as ok] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
server_1 |     at found (/server/api/blueprints/find.js:76:9)
server_1 |     at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
server_1 |     at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
server_1 |     at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
server_1 |     at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
server_1 |     at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
server_1 |     at returnResults (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:356:9)
server_1 |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:251:16
server_1 |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
server_1 |     at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:121:20)
server_1 |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:425:11
server_1 |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:564:5
server_1 |     at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:121:20)
server_1 |     at _buildChildOpts (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:453:9)
```

**Comment by mgenev** [comment]
When I run the project without --docker flag, the first error doesn't happen, but the 2nd one does which makes me wonder if it's a new version of the blueprint or something

**Comment by Globegitter** [comment]
Should be fixed using the latest master.
