### ISSUE TITLE
Error: Cannot find module 'lodash/collection/forEach'

### ISSUE THREAD

**Issue by okket** [artificialio/sane#96]
Looks like new alpha installs are currently broken: "sane new" finishes, but "sane up" is unable to start the Sails server:
```
server   | 
server   | info: Starting app...
server   | 
client   | version: 0.2.0-beta.1
server   | module.js:338
server   |     throw err;
server   |     ^
server   | Error: Cannot find module 'lodash/collection/forEach'
server   |     at Function.Module._resolveFilename (module.js:336:15)
server   |     at Function.Module._load (module.js:278:25)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at Object.<anonymous> (/Users/okketimm/code/js/sanenew/server/api/services/Ember.js:7:17)
server   |     at Module._compile (module.js:460:26)
server   |     at Object.Module._extensions..js (module.js:478:10)
server   |     at Module.load (module.js:355:32)
server   |     at Function.Module._load (module.js:310:12)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:129:29
server   |     at Array.forEach (native)
server   |     at requireAll (/usr/local/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
server   |     at buildDictionary (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
server   |     at Function.module.exports.optional (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
```

**Comment by Globegitter** [comment]
Yeah, seems there is something up. Make sure you have the latest lodash 3.x installed in your project and let me know if that fixes it.

**Comment by Globegitter** [comment]
Yep, manually installing the latest lodash in your `/server` folder should fix this. This fix will come in the next alpha.

**Comment by okket** [comment]
Yes, this works, thank you.
